### ISSUE TITLE
Search icon missing in Chrome on Linux

### ISSUE THREAD

**Issue by jaimemarijke** [thatneat/climbplan#18]
This could be fixed by changing that search icon to be a real icon instead of a character

![selection_269](https://cloud.githubusercontent.com/assets/5770688/16625261/777d571c-4358-11e6-8d36-0f52135150d1.png)

**Comment by jason-curtis** [comment]
yeah or maybe exploring using TypeKit fonts or something of the like. Seems like the font we're using here (family = Roboto) just doesn't implement that character in the ubuntu implementation. At this day in age we should be able to get basic iconography without serving static files for them.

**Comment by Spectre5** [comment]
Is this only a chrome issue?  It works find on Chromium in Linux

**Comment by jason-curtis** [comment]
maybe the font got upgraded? chromium seems good enough.
